# Site settings
title: Ultra/Beyond Città Studi
email: beyond-cittastudi@polimi.it
description: > # this means to ignore newlines until "baseurl:"
  Crowdsourcing architecture with photo-contests. Ultra/Beyond&nbsp;Città&nbsp;Studi, april 4 > may 8 2016, is one of the shows of Campus&nbsp;&amp;&nbsp;Controcampus, organized by XXI&nbsp;Triennale Esposizione Internazionale Milano 2016, open until September, 12 @ Politecnico di Milano.
baseurl: ""
url: "http://beyondcittastudi.junglestar.org"
version: 0.3.0

# Build settings
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
permalink: /:categories/:title/

exclude:
 - Gemfile
 - Gemfile.lock
 - package.json
 - DS_Store
 - Icon
 - .workinprogress

# ship crew personas
github: toybreaker
instagram:
  # instuff
  userId: #''
  clientId: #''
  accessToken: #''
  profile: 'beyondcittastudi'
google:
  plus: #username
  analytics: 'UA-74710021-1'
  verify: 'GH4oVo3DLVE-iOQdlqwaeVHCmb40aOrqCHdSNxS_dC8'

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
